/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'surface-dim': 'rgb(var(--surface-dim) / <alpha-value>)',
        'surface-bright': 'rgb(var(--surface-bright) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--surface-container-lowest) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--surface-container-low) / <alpha-value>)',
        'surface-container': 'rgb(var(--surface-container) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--surface-container-highest) / <alpha-value>)',
        'on-surface': 'rgb(var(--on-surface) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--on-surface-variant) / <alpha-value>)',
        outline: 'rgb(var(--outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--outline-variant) / <alpha-value>)',
        error: 'rgb(var(--error) / <alpha-value>)',
        'error-container': 'rgb(var(--error-container) / <alpha-value>)',
        'on-error-container': 'rgb(var(--on-error-container) / <alpha-value>)',
        primary: {
          50: 'rgb(var(--primary-container) / .35)',
          100: 'rgb(var(--primary-container) / .7)',
          200: 'rgb(var(--primary-fixed-dim) / <alpha-value>)',
          300: 'rgb(var(--primary-fixed) / <alpha-value>)',
          400: 'rgb(var(--primary) / .78)',
          500: 'rgb(var(--primary) / .9)',
          600: 'rgb(var(--primary) / <alpha-value>)',
          700: 'rgb(var(--primary-dim) / <alpha-value>)',
          800: 'rgb(var(--primary-dim) / <alpha-value>)',
          900: 'rgb(var(--on-primary-container) / <alpha-value>)',
          950: 'rgb(var(--on-primary-fixed) / <alpha-value>)',
        },
        secondary: {
          50: '#f4f9f4',
          100: '#e6f2e6',
          200: '#cce5cd',
          300: '#99cb9b',
          400: '#66b069',
          500: '#3d9641',
          600: '#2c7830',
          700: '#255f28',
          800: '#214c23',
          900: '#1c3f1e',
          950: '#0e2210',
        },
        accent: {
          50: '#fef7f0',
          100: '#fdedd9',
          200: '#f9d9b0',
          300: '#f5be7e',
          400: '#f09a47',
          500: '#ec7f21',
          600: '#de6316',
          700: '#b84b14',
          800: '#933d17',
          900: '#773416',
          950: '#421908',
        }
      },
      fontFamily: {
        sans: ['Instrument Sans', 'system-ui', '-apple-system', 'sans-serif'],
        body: ['Instrument Sans', 'system-ui', '-apple-system', 'sans-serif'],
        headline: ['Plus Jakarta Sans', 'Instrument Sans', 'system-ui', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-in': 'slideIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideIn: {
          '0%': { transform: 'translateX(-10px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}